version: '3'

services:
  api-gpt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Rest_CLinet_Helper
      - 4000:4000
    restart: always
    networks:
      - home
networks:
  home:
    driver: bridge
