version: '3'

services:
  api-gpt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ObsdianTegBot
    ports:
      - 4001:4001
    restart: always
    networks:
      - home
networks:
  home:
    driver: bridge
