@baseUrl = http://localhost:3003
### New User
POST {{baseUrl}}/users
content-type: application/json

{
 "telegramUserId": "3243223dfAfd_Svd!", "username": "user6"
}

### Get All Users
GET {{baseUrl}}/users/

### Get User
GET {{baseUrl}}/users/3243223dfAfd_Svd!

###Delete User 
DELETE {{baseUrl}}/users/3243223dfAfd_Svd!

